name: BuildPackage

on: [workflow_dispatch,push]

jobs:

  buildAllPackage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, macos-latest ]

    steps:
      - name: checkout_actions
        uses: actions/checkout@v3
        
      - name: SetupJDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'corretto'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          
      - name: SetupKotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.6.10
          run: kotlinc -script build.gradle.kts

      - name: GradleBuild
        uses: gradle/gradle-build-action@v2
        with:
          run: gradle package
          
      - name: UploadWindows
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/composecbinaries/main/msi
          
      - name: UploadLinux
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/composecbinaries/main/deb
          
      - name: UploadmacOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/composecbinaries/main/dmg
